apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-main.yml
  - deployment-worker.yml
  - service.yml
  - route.yml
  - autoscaling.yml

configMapGenerator:
- name: locust-script
  files:
  - locustfile.py
- name: requirements
  files:
  - requirements